# Generated by Django 5.0 on 2023-12-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_alter_expertprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='is_expert',
            field=models.BooleanField(default=False),
        ),
    ]
