# Generated by Django 5.0 on 2023-12-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_expertprofile_is_expert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertprofile',
            name='is_expert',
        ),
    ]
