# Generated by Django 5.0 on 2023-12-07 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_remove_expertprofile_is_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertexperience',
            name='expert_profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='experts.expertprofile'),
            preserve_default=False,
        ),
    ]
