# Generated by Django 5.0 on 2023-12-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_expert_profile'),
        ('experts', '0006_remove_expertexperience_expert_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='courses',
            field=models.ManyToManyField(to='courses.course'),
        ),
    ]
