# Generated by Django 5.0 on 2023-12-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0007_expertprofile_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertprofile',
            name='courses',
        ),
    ]
