# Generated by Django 5.0 on 2023-12-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0008_remove_expertprofile_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertexperience',
            name='experience_field',
            field=models.CharField(choices=[('programers', 'Programers'), ('Story', 'Story'), ('Poetry', 'Poetry')], default='Story', max_length=56),
        ),
    ]
