# Generated by Django 5.0 on 2023-12-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0009_expertexperience_experience_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertexperience',
            name='experience_field',
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='experience_field',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Law', 'Law'), ('Sciences', 'Sciences')], default='Sciences', max_length=56),
        ),
    ]
