# Generated by Django 5.0 on 2023-12-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_user_coursecontent'),
        ('experts', '0004_remove_expertprofile_is_expert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='expert_profile',
            field=models.ManyToManyField(to='experts.expertprofile'),
        ),
    ]
