# Generated by Django 5.0 on 2023-12-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_user_course_expert_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='expert_profile',
        ),
    ]
