# Generated by Django 5.0 on 2023-12-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_subcriptions_remove_course_user_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='addition_time',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
