# Generated by Django 5.0 on 2023-12-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_addition_time_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='addition_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
