# Generated by Django 5.0 on 2023-12-12 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='addition_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
